version: "3"
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: test-runner
    environment:
      - NEO4J_TEST_URL=http://neo4j:7474/db/data
    command: ["go", "test", "-mod=readonly", "-v", "-race", "./..."]
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:3.4.10-enterprise
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7475:7474"
      - "7688:7687"
