version: "3"
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    container_name: test-runner
    environment:
      - NEO4J_TEST_URL=bolt://neo4j:7687
    command: ["go", "test", "-mod=readonly", "-v", "-race", "./..."]
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.3-enterprise
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7475:7474"
      - "7688:7687"
