[[constraint]]
  name = "github.com/Financial-Times/go-fthealth"
  version = "0.4.0"

[[constraint]]
  name = "github.com/Financial-Times/neo-utils-go"
  version = "=1.0.4"

[[constraint]]
  branch = "develop"
  name = "github.com/jmcvetta/neoism"

[prune]
  go-tests = true
  unused-packages = true
