version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@dev:6711dae

workflows:
  tests_and_docker:
    jobs:
      - ft-golang-ci/build-and-test:
          name: build-and-test-project
          executor-name:
            name: ft-golang-ci/default-with-neo4j
            neo4j-image-version: 3.5.28-enterprise
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context: cm-team-snyk
          executor-name:
            name: ft-golang-ci/scanner
            circleci-golang-image-version: "1.17"
