apiVersion: v1
description: content-collection-rw-neo4j Helm chart for Kubernetes
name: content-collection-rw-neo4j
version: 0.0.0  # this entry can be left untouched as it is automatically handled by Jenkins pipeline
