# Default values for content-collection-rw-neo4j.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/content-collection-rw-neo4j
  pullPolicy: IfNotPresent
resources:
 limits:
   memory: 256Mi
env:
  APP_PORT: 8080
